### ISSUE TITLE
Apple 2e ROMs

### ISSUE THREAD

**Issue by varmfskii** [vsladkov/reload-emulator#2]
for commit 07240ed249e2841b22aa66d99a53ed12a79fa610:

reload-emulator/platforms/pico-6502/systems/apple2e/src/apple2e.c
line 17: roms/apple2ee_roms.h not found: probably just a set of ROMs not described in the roms_md5.txt file
line 91: apple2e_rom undeclared: this is declared as a variable in roms/apple2e_roms.h but roms/apple2e_roms.h is commented out
line 92: apple2e_character_rom undeclared: roms/apple2e_roms.h has apple2_character rom as specified in roms_md5.txt, changing to apple2e_character_rom has no effect.

compiles if apple2e_roms.h is renamed to apple2ee_roms.h

reload-emulator/platforms/pico-6502/systems/apple2e/src/oric.c
line 84: oric_boot_rom undeclared: not present in any file including documentation. Should this be oric_fdc_rom?

**Comment by vsladkov** [comment]
There are 2 versions of ROMs - Apple //e and Apple //e Enhanced, both will work, but the second is better because the CPU is 65C02.

Boot rooms are moved to controller headers. It should be oric_fdc_rom. Fixed.

Better description of system rom added with example files and MD5 checksums.
