### ISSUE TITLE
Apple II custom image built do not boot since  commit #223faa5

### ISSUE THREAD

**Issue by kris92** [vsladkov/reload-emulator#3]
Hello,
Just for your information.
Since commit #223faa5, image built from source code do not work anymore if you try to boot immediately after flashing the pico and if the pico is attached to the computer without any USB drive attached.

The thing is you disabled hdc_internal_flash. So we are looping on apple2e.h line 277 
```
> while (!msc_inquiry_complete) {
```

It was my first attempt to build the project with a Neo6502 board. So It took some time to understand why the board didn't even beep at boot ;-)

**Comment by vsladkov** [comment]
Hi,

It is configured now by default to work with USB and Total Replay. This could be changed with hdc_internal_flash = true in apple2e.c / apple2.c, and proper configuration of images in apple2_images.h.

BR,

Veselin
