### ISSUE TITLE
Distorted sound

### ISSUE THREAD

**Issue by tomptz** [vsladkov/reload-emulator#4]
I am facing distorted/crackling sounds. Is this a bug in the emulation or a problem with my hardware?

**Comment by jsavidan** [comment]
I am facing exactly the same issue with a board I received 2d ago with the pre-flashed apple II emulator. Any hint would be greatly appreciated. Thanks

**Comment by vsladkov** [comment]
Audio subsystem is upgraded for all emulators. Sound is much better now.
