### ISSUE TITLE
6502 Processor

### ISSUE THREAD

**Issue by DanielTelles91** [vsladkov/reload-emulator#5]
Is this emulator compatible with the 6502 processor? I assembled the circuit on the breadboard using the 6502 processor (From an old Apple 2) but unfortunately it is not loading the system correctly.

Thanks,
Daniel.

**Comment by vsladkov** [comment]
Hi,

It should be CMOS version because the clock is not perfect and NMOS
versions have strong requirements on that.

BR,

Veselin
